/**
 * Design-system assembly: tokens + recipes (+ optional raw CSS) compiled
 * into the artifacts a DS package ships — per-component CSS files, a
 * combined index, and theme metadata for the runtime registry.
 */
import type { ManifestComponent, RoleDecl, ZeroManifest } from './contract.js';
import { DEFAULT_ROLES, defaultSwatch, resolveRoles, resolveSizes } from './contract.js';
import type { CustomTokenDecl, RolesDecl, SystemTokens, TokensInput } from './tokens.js';
import { compileTokensCss } from './targets/web/tokens-css.js';
import type { RecipeInput } from './recipes.js';
import { compileRecipeCss } from './targets/web/recipe-css.js';

export interface DesignSystemInput<
    R extends RolesDecl = RolesDecl,
    T extends SystemTokens = SystemTokens,
> {
    name: string;
    tokens: TokensInput<R, T>;
    recipes: RecipeInput[];
    /** Raw CSS appended verbatim after the compiled recipes (escape hatch). */
    css?: string[];
}

/** Identity with typing — the authoring entry point. */
export function defineDesignSystem<
    const R extends RolesDecl = typeof DEFAULT_ROLES,
    const T extends SystemTokens = SystemTokens,
>(input: DesignSystemInput<R, T>): DesignSystemInput<R, T> {
    return input;
}

export interface CompiledTheme {
    name: string;
    colorScheme: 'light' | 'dark';
    pair?: string;
    swatch: Record<string, string>;
}

export interface CompiledDesignSystem {
    name: string;
    tokensCss: string;
    /** component scope → compiled recipe CSS. */
    componentCss: Record<string, string>;
    /** tokens + all components + raw css, in order. */
    indexCss: string;
    themes: CompiledTheme[];
    /** The DS's declared token vocabulary — emitted into the DS manifest. */
    tokens: {
        roles: Record<string, RoleDecl>;
        /** The DS's `size` axis vocabulary, resolved (declared, else recommended). */
        sizes: string[];
        /** The DS's declared `variant` axis vocabulary ([] when undeclared). */
        variants: string[];
        /** Declared custom variant axes: axis name → values ({} when undeclared). */
        axes: Record<string, string[]>;
        custom: Record<string, CustomTokenDecl>;
        breakpoints: Record<string, string>;
        /** DS-level values per category id, e.g. `{ radius: { field: '0.5rem' } }`. */
        system: Record<string, unknown>;
        /** Overrides applied to dark-scheme themes. */
        systemDark: Record<string, unknown>;
        /**
         * Every custom property this design system emits, flat and sorted —
         * what editor completion, the docs site and cross-platform emitters
         * want, rather than re-deriving it from the grammar.
         */
        properties: string[];
    };
}

/**
 * Every custom property the compiled tokens.css defines, sorted and deduped.
 *
 * Read back off the emitted CSS rather than re-derived from the declaration,
 * so it cannot drift from what the design system actually ships — including
 * derived tokens like `--color-<role>-soft` that no declaration lists.
 */
function emittedProperties(tokensCss: string): string[] {
    const found = new Set<string>();
    for (const [, prop] of tokensCss.matchAll(/^\s*(--[\w-]+)\s*:/gm)) found.add(prop!);
    return [...found].sort();
}

export function compileDesignSystem<R extends RolesDecl, T extends SystemTokens>(
    ds: DesignSystemInput<R, T>,
    manifest: Pick<ZeroManifest, 'components'>,
): CompiledDesignSystem {
    const byScope = new Map<string, ManifestComponent>(
        manifest.components.map((c) => [c.scope, c]),
    );

    const tokensCss = compileTokensCss(ds.tokens);

    const componentCss: Record<string, string> = {};
    for (const recipe of ds.recipes) {
        const component = byScope.get(recipe.component);
        if (!component) {
            const known = [...byScope.keys()].join(', ');
            throw new Error(
                `[zero-kit] design system "${ds.name}" has a recipe for unknown component "${recipe.component}" (known: ${known})`,
            );
        }
        if (componentCss[recipe.component]) {
            throw new Error(`[zero-kit] duplicate recipe for component "${recipe.component}"`);
        }
        componentCss[recipe.component] = compileRecipeCss(recipe, component, {
            breakpoints: ds.tokens.breakpoints,
        });
    }

    const rawCss = (ds.css ?? []).join('\n');
    const indexCss = [
        `/* ${ds.name} — generated by @sigx/zero-kit. Do not edit. */`,
        tokensCss,
        ...Object.values(componentCss),
        ...(rawCss ? [`@layer zero.recipes {\n${rawCss}\n}`] : []),
    ].join('\n');

    const roles = resolveRoles(ds.tokens.roles);
    const swatch = ds.tokens.swatch ?? defaultSwatch(Object.keys(roles));
    const themes: CompiledTheme[] = Object.entries(ds.tokens.themes).map(([name, theme]) => {
        const colors = theme.colors as Record<string, string>;
        return {
            name,
            colorScheme: theme.colorScheme,
            ...(theme.pair ? { pair: theme.pair } : {}),
            swatch: Object.fromEntries(
                swatch.flatMap((t) => (colors[t] ? [[t, colors[t]]] : [])),
            ),
        };
    });

    return {
        name: ds.name,
        tokensCss,
        componentCss,
        indexCss,
        themes,
        tokens: {
            roles,
            sizes: [...resolveSizes(ds.tokens.sizes)],
            variants: [...(ds.tokens.variants ?? [])],
            axes: Object.fromEntries(
                Object.entries(ds.tokens.axes ?? {}).map(([axis, values]) => [axis, [...values]]),
            ),
            custom: ds.tokens.custom ?? {},
            breakpoints: ds.tokens.breakpoints ?? {},
            system: (ds.tokens.system ?? {}) as Record<string, unknown>,
            systemDark: (ds.tokens.systemDark ?? {}) as Record<string, unknown>,
            properties: emittedProperties(tokensCss),
        },
    };
}
