/**
 * Design-system assembly: tokens + recipes (+ optional raw CSS) compiled
 * into the artifacts a DS package ships — per-component CSS files, a
 * combined index, and theme metadata for the runtime registry.
 */
import type { ManifestComponent, ZeroManifest } from './contract.js';
import type { TokensInput } from './tokens.js';
import { compileTokensCss } from './tokens.js';
import type { RecipeInput } from './recipes.js';
import { compileRecipeCss } from './recipes.js';

export interface DesignSystemInput {
    name: string;
    tokens: TokensInput;
    recipes: RecipeInput[];
    /** Raw CSS appended verbatim after the compiled recipes (escape hatch). */
    css?: string[];
}

/** Identity with typing — the authoring entry point. */
export function defineDesignSystem(input: DesignSystemInput): DesignSystemInput {
    return input;
}

export interface CompiledTheme {
    name: string;
    colorScheme: 'light' | 'dark';
    pair?: string;
    swatch: Record<string, string>;
}

export interface CompiledDesignSystem {
    name: string;
    tokensCss: string;
    /** component scope → compiled recipe CSS. */
    componentCss: Record<string, string>;
    /** tokens + all components + raw css, in order. */
    indexCss: string;
    themes: CompiledTheme[];
}

const SWATCH_TOKENS = ['primary', 'secondary', 'accent', 'neutral', 'base-100', 'base-content'] as const;

export function compileDesignSystem(
    ds: DesignSystemInput,
    manifest: Pick<ZeroManifest, 'components'>,
): CompiledDesignSystem {
    const byScope = new Map<string, ManifestComponent>(
        manifest.components.map((c) => [c.scope, c]),
    );

    const tokensCss = compileTokensCss(ds.tokens);

    const componentCss: Record<string, string> = {};
    for (const recipe of ds.recipes) {
        const component = byScope.get(recipe.component);
        if (!component) {
            const known = [...byScope.keys()].join(', ');
            throw new Error(
                `[zero-kit] design system "${ds.name}" has a recipe for unknown component "${recipe.component}" (known: ${known})`,
            );
        }
        if (componentCss[recipe.component]) {
            throw new Error(`[zero-kit] duplicate recipe for component "${recipe.component}"`);
        }
        componentCss[recipe.component] = compileRecipeCss(recipe, component);
    }

    const rawCss = (ds.css ?? []).join('\n');
    const indexCss = [
        `/* ${ds.name} — generated by @sigx/zero-kit. Do not edit. */`,
        tokensCss,
        ...Object.values(componentCss),
        ...(rawCss ? [`@layer zero.recipes {\n${rawCss}\n}`] : []),
    ].join('\n');

    const themes: CompiledTheme[] = Object.entries(ds.tokens.themes).map(([name, theme]) => ({
        name,
        colorScheme: theme.colorScheme,
        ...(theme.pair ? { pair: theme.pair } : {}),
        swatch: Object.fromEntries(
            SWATCH_TOKENS.flatMap((t) => (theme.colors[t] ? [[t, theme.colors[t]]] : [])),
        ),
    }));

    return { name: ds.name, tokensCss, componentCss, indexCss, themes };
}
