/**
 * Design-system assembly: tokens + recipes (+ optional raw CSS) compiled
 * into the artifacts a DS package ships — per-component CSS files, a
 * combined index, and theme metadata for the runtime registry.
 */
import type { ManifestComponent, RoleDecl, ZeroManifest } from './contract.js';
import { DEFAULT_ROLES, resolveRoles } from './contract.js';
import type { CustomTokenDecl, RolesDecl, TokensInput } from './tokens.js';
import { compileTokensCss } from './tokens.js';
import type { RecipeInput } from './recipes.js';
import { compileRecipeCss } from './recipes.js';

export interface DesignSystemInput<R extends RolesDecl = RolesDecl> {
    name: string;
    tokens: TokensInput<R>;
    recipes: RecipeInput[];
    /** Raw CSS appended verbatim after the compiled recipes (escape hatch). */
    css?: string[];
}

/** Identity with typing — the authoring entry point. */
export function defineDesignSystem<const R extends RolesDecl = typeof DEFAULT_ROLES>(
    input: DesignSystemInput<R>,
): DesignSystemInput<R> {
    return input;
}

export interface CompiledTheme {
    name: string;
    colorScheme: 'light' | 'dark';
    pair?: string;
    swatch: Record<string, string>;
}

export interface CompiledDesignSystem {
    name: string;
    tokensCss: string;
    /** component scope → compiled recipe CSS. */
    componentCss: Record<string, string>;
    /** tokens + all components + raw css, in order. */
    indexCss: string;
    themes: CompiledTheme[];
    /** The DS's declared token vocabulary — emitted into the DS manifest. */
    tokens: {
        roles: Record<string, RoleDecl>;
        custom: Record<string, CustomTokenDecl>;
        breakpoints: Record<string, string>;
    };
}

/** Default swatch: the first four declared roles plus the base surfaces. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- variance-erased internal plumbing
const swatchTokens = (tokens: TokensInput<any>, roles: Record<string, RoleDecl>): string[] =>
    tokens.swatch ?? [...Object.keys(roles).slice(0, 4), 'base-100', 'base-content'];

export function compileDesignSystem<R extends RolesDecl>(
    ds: DesignSystemInput<R>,
    manifest: Pick<ZeroManifest, 'components'>,
): CompiledDesignSystem {
    const byScope = new Map<string, ManifestComponent>(
        manifest.components.map((c) => [c.scope, c]),
    );

    const tokensCss = compileTokensCss(ds.tokens);

    const componentCss: Record<string, string> = {};
    for (const recipe of ds.recipes) {
        const component = byScope.get(recipe.component);
        if (!component) {
            const known = [...byScope.keys()].join(', ');
            throw new Error(
                `[zero-kit] design system "${ds.name}" has a recipe for unknown component "${recipe.component}" (known: ${known})`,
            );
        }
        if (componentCss[recipe.component]) {
            throw new Error(`[zero-kit] duplicate recipe for component "${recipe.component}"`);
        }
        componentCss[recipe.component] = compileRecipeCss(recipe, component);
    }

    const rawCss = (ds.css ?? []).join('\n');
    const indexCss = [
        `/* ${ds.name} — generated by @sigx/zero-kit. Do not edit. */`,
        tokensCss,
        ...Object.values(componentCss),
        ...(rawCss ? [`@layer zero.recipes {\n${rawCss}\n}`] : []),
    ].join('\n');

    const roles = resolveRoles(ds.tokens.roles);
    const swatch = swatchTokens(ds.tokens, roles);
    const themes: CompiledTheme[] = Object.entries(ds.tokens.themes).map(([name, theme]) => {
        const colors = theme.colors as Record<string, string>;
        return {
            name,
            colorScheme: theme.colorScheme,
            ...(theme.pair ? { pair: theme.pair } : {}),
            swatch: Object.fromEntries(
                swatch.flatMap((t) => (colors[t] ? [[t, colors[t]]] : [])),
            ),
        };
    });

    return {
        name: ds.name,
        tokensCss,
        componentCss,
        indexCss,
        themes,
        tokens: {
            roles,
            custom: ds.tokens.custom ?? {},
            breakpoints: ds.tokens.breakpoints ?? {},
        },
    };
}
