/**
 * Lynx design-system compile + artifacts: the lynx counterpart of
 * `compileDesignSystem` + `writeArtifacts`, emitted BESIDE the web artifacts
 * under `dist/lynx/`:
 *
 * ```
 * dist/lynx/tokens.css              (.zx-root + per-theme class blocks, literals)
 * dist/lynx/components/<scope>.css  (class-grammar recipes)
 * dist/lynx/index.css               (tokens + all components, one stylesheet)
 * dist/lynx/manifest.json           (the DS manifest + lynx envelope: target,
 *                                    classGrammarVersion, capability summary)
 * ```
 *
 * The manifest reuses the web compile's themes/tokens/components — one
 * design system, one truth about its vocabulary; only the delivery differs.
 * The capability report also lands in the web `report.json` under `lynx`
 * (wired by `runStandardBuild`), so one file still answers "what did this
 * design system ship".
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import { Ajv2020 } from 'ajv/dist/2020.js';
import type { ValidateFunction } from 'ajv/dist/2020.js';
import type { ZeroManifest } from '../../contract.js';
import { TOKEN_KEY_PATTERN } from '../../contract.js';
import type { CompiledDesignSystem, DesignSystemInput } from '../../design-system.js';
import { resolveRecipeForTarget } from '../../recipes.js';
import type { DesignSystemManifest } from '../../artifacts.js';
import type { LynxCapabilityReport } from './capabilities.js';
import { emptyReport } from './capabilities.js';
import { CLASS_GRAMMAR_VERSION } from './class-names.js';
import { compileLynxRecipeCss } from './recipe-css.js';
import { compileLynxTokensCss } from './tokens-css.js';

export interface CompiledLynxTarget {
    tokensCss: string;
    componentCss: Record<string, string>;
    indexCss: string;
    report: LynxCapabilityReport;
}

/** The lynx manifest: the DS manifest's content plus the lynx envelope. */
export interface LynxTargetManifest extends Omit<DesignSystemManifest, '$schema'> {
    $schema: string;
    target: 'lynx';
    classGrammarVersion: number;
    /** Counts only — the findings themselves live in report.json under `lynx`. */
    capabilities: { translated: number; dropped: number };
}

/** Compile the lynx target for one design system. */
export function compileDesignSystemLynx(
    ds: DesignSystemInput,
    manifest: Pick<ZeroManifest, 'components'>,
): CompiledLynxTarget {
    const report = emptyReport();
    const tokensCss = compileLynxTokensCss(ds.tokens, report);

    const byScope = new Map(manifest.components.map((c) => [c.scope, c]));
    const componentCss: Record<string, string> = {};
    for (const recipe of ds.recipes) {
        const component = byScope.get(recipe.component);
        if (!component) {
            const known = [...byScope.keys()].join(', ');
            throw new Error(
                `[zero-kit] design system "${ds.name}" has a recipe for unknown component "${recipe.component}" (known: ${known})`,
            );
        }
        // The lynx view: shared sections + targets.lynx merged. A shared raw
        // `css` block is web spelling by definition — the resolver already
        // withholds it from this view; record the drop so the report says so.
        if (recipe.css?.trim()) {
            report.dropped.push({
                where: `lynx recipe for "${recipe.component}"`,
                what: 'css (raw stylesheet escape hatch)',
                detail: 'shared raw CSS is web spelling and is not emitted on this target — move it into targets.web (or author a lynx counterpart in targets.lynx.css)',
            });
        }
        const css = compileLynxRecipeCss(resolveRecipeForTarget(recipe, 'lynx'), component, report);
        if (css) componentCss[recipe.component] = css;
    }

    // `ds.css` (the raw web escape hatch) is deliberately NOT appended — it is
    // web spelling by definition and drops with one report entry.
    if ((ds.css ?? []).some((c) => c.trim())) {
        report.dropped.push({
            where: `lynx design system "${ds.name}"`,
            what: 'css (raw stylesheet escape hatch)',
            detail: 'raw web CSS is not emitted on this target',
        });
    }

    const indexCss = [
        `/* ${ds.name} — lynx target, generated by @sigx/zero-kit. Do not edit. */`,
        tokensCss,
        ...Object.values(componentCss),
    ].join('\n');

    return { tokensCss, componentCss, indexCss, report };
}

const LYNX_MANIFEST_SCHEMA_URL = 'https://signalxjs.github.io/zero/schemas/lynx-manifest.schema.json';

const require = createRequire(import.meta.url);

/**
 * The schema, loaded from wherever this module runs — same two-location
 * resolution as the DS manifest validator in `artifacts.ts` (`dist/schemas/`
 * in the published package, `../schemas/` from source under test aliases).
 */
let validateLynxManifest: ValidateFunction | null = null;
function lynxManifestValidator(): ValidateFunction {
    if (validateLynxManifest) return validateLynxManifest;
    let path: string;
    try {
        path = require.resolve('../../schemas/lynx-manifest.schema.json');
    } catch {
        path = require.resolve('../../../schemas/lynx-manifest.schema.json');
    }
    const raw = readFileSync(path, 'utf8');
    const ajv = new Ajv2020({ allErrors: true, strict: true, allowUnionTypes: true });
    return (validateLynxManifest = ajv.compile(JSON.parse(raw) as Record<string, unknown>));
}

/**
 * Write the lynx artifacts under `<outDir>/lynx/`. The manifest content
 * comes from the WEB compile (`compiled`) — same themes, tokens and wired
 * axes; the envelope says how this copy is delivered.
 */
export async function writeLynxArtifacts(
    compiled: CompiledDesignSystem,
    lynx: CompiledLynxTarget,
    manifest: DesignSystemManifest,
    outDir: string,
): Promise<string[]> {
    const lynxDir = join(outDir, 'lynx');
    const componentsDir = join(lynxDir, 'components');
    await mkdir(componentsDir, { recursive: true });

    const written: string[] = [];
    const write = async (path: string, content: string) => {
        await writeFile(path, content.endsWith('\n') ? content : content + '\n');
        written.push(path);
    };

    await write(join(lynxDir, 'tokens.css'), lynx.tokensCss);
    for (const [scope, css] of Object.entries(lynx.componentCss)) {
        // Same backstop as the web artifacts: the scope IS the filename.
        if (!TOKEN_KEY_PATTERN.test(scope)) {
            throw new Error(
                `[zero-kit] compiled scope "${scope}" is not a kebab-case identifier — it becomes the lynx/components/<scope>.css filename, so anything else could escape the output directory`,
            );
        }
        await write(join(componentsDir, `${scope}.css`), css);
    }
    await write(join(lynxDir, 'index.css'), lynx.indexCss);

    const lynxManifest: LynxTargetManifest = {
        ...manifest,
        $schema: LYNX_MANIFEST_SCHEMA_URL,
        target: 'lynx',
        classGrammarVersion: CLASS_GRAMMAR_VERSION,
        capabilities: {
            translated: lynx.report.translated.length,
            dropped: lynx.report.dropped.length,
        },
    };
    // Self-validation, exactly like the DS manifest: a manifest the schema
    // rejects fails the build that PRODUCES it, not the app that reads it.
    // JSON-roundtripped so the thing validated is byte-for-byte the thing
    // written.
    const emitted: unknown = JSON.parse(JSON.stringify(lynxManifest));
    const validate = lynxManifestValidator();
    if (!validate(emitted)) {
        const details = validate.errors
            ?.map((e) => `  ${e.instancePath || '(root)'} ${e.message ?? ''}`)
            .join('\n');
        throw new Error(
            `[zero-kit] the lynx manifest for "${compiled.name}" does not validate against `
            + `lynx-manifest.schema.json — refusing to write it:\n${details}`,
        );
    }
    await write(join(lynxDir, 'manifest.json'), JSON.stringify(emitted, null, 2));
    return written;
}
