// carbon — generated by @sigx/zero-kit. Do not edit.
//
// Vendor-named component API (issue #179): zero's components under this
// design system's prop names, narrowed to what its recipes wire.
// Self-contained — nothing here augments ZeroVocabulary, no /register
// import is needed or consulted. The rendered attributes are unchanged:
// a routed vendor value renders the zero-spelled data-* attribute.
import type { Adapted, AdaptedStatics } from '@sigx/zero/adapt';
import type { Button as ZButton } from '@sigx/zero/button';

type ZeroAxisProp = 'color' | 'size' | 'variant' | 'axes' | 'mods';

/** button — kind ← variant (2 respelled); hasIconOnly ← mods.icon-only; isExpressive ← mods.expressive; useZebraStyles ← mods.zebra. Attributes stay zero-spelled. */
type ButtonProps = {
    'kind'?: 'primary' | 'secondary' | 'tertiary' | 'ghost' | 'danger' | 'danger--tertiary' | 'danger--ghost';
    'hasIconOnly'?: boolean;
    'isExpressive'?: boolean;
    'useZebraStyles'?: boolean;
};
type ButtonAdapted = Adapted<typeof ZButton, ZeroAxisProp | 'hasIconOnly' | 'isExpressive' | 'kind' | 'useZebraStyles', ButtonProps>;
export declare const Button: ButtonAdapted & { Root: ButtonAdapted };
