// heroui — generated by @sigx/zero-kit. Do not edit.
//
// Vendor-named component API (issue #179): zero's components under this
// design system's prop names, narrowed to what its recipes wire.
// Self-contained — nothing here augments ZeroVocabulary, no /register
// import is needed or consulted. The rendered attributes are unchanged:
// a routed vendor value renders the zero-spelled data-* attribute.
import type { Adapted, AdaptedStatics } from '@sigx/zero/adapt';
import type { Button as ZButton } from '@sigx/zero/button';
import type { Tabs as ZTabs } from '@sigx/zero/tabs';
import type { Switch as ZSwitch } from '@sigx/zero/switch';
import type { Checkbox as ZCheckbox } from '@sigx/zero/checkbox';
import type { Select as ZSelect } from '@sigx/zero/select';
import type { Dialog as ZDialog } from '@sigx/zero/dialog';
import type { Field as ZField } from '@sigx/zero/field';
import type { Toast as ZToast } from '@sigx/zero/toast';

type ZeroAxisProp = 'color' | 'size' | 'variant' | 'axes' | 'mods';

/** button — variant ← variant; isIconOnly ← mods.icon-only; isPending ← mods.pending. Attributes stay zero-spelled. */
type ButtonProps = {
    size?: 'sm' | 'md' | 'lg';
    'variant'?: 'primary' | 'secondary' | 'tertiary' | 'outline' | 'ghost' | 'danger' | 'danger-soft';
    'isIconOnly'?: boolean;
    'isPending'?: boolean;
};
type ButtonAdapted = Adapted<typeof ZButton, ZeroAxisProp | 'isIconOnly' | 'isPending' | 'variant', ButtonProps>;
export declare const Button: ButtonAdapted & { Root: ButtonAdapted };

/** tabs — no vendor route; the wired surface keeps zero's names. */
type TabsProps = {
    size?: 'sm' | 'md' | 'lg';
};
type TabsAdapted = Adapted<typeof ZTabs, ZeroAxisProp, TabsProps>;
export declare const Tabs: TabsAdapted & AdaptedStatics<typeof ZTabs> & { Root: TabsAdapted };

/** switch — no vendor route; the wired surface keeps zero's names. */
type SwitchProps = {
    size?: 'sm' | 'md' | 'lg';
};
type SwitchAdapted = Adapted<typeof ZSwitch, ZeroAxisProp, SwitchProps>;
export declare const Switch: SwitchAdapted & AdaptedStatics<typeof ZSwitch> & { Root: SwitchAdapted };

/** checkbox — no vendor route; the wired surface keeps zero's names. */
type CheckboxProps = {
    size?: 'sm' | 'md' | 'lg';
};
type CheckboxAdapted = Adapted<typeof ZCheckbox, ZeroAxisProp, CheckboxProps>;
export declare const Checkbox: CheckboxAdapted & AdaptedStatics<typeof ZCheckbox> & { Root: CheckboxAdapted };

/** select — no vendor route; the wired surface keeps zero's names. */
type SelectProps = {
    size?: 'sm' | 'md' | 'lg';
};
type SelectAdapted = Adapted<typeof ZSelect, ZeroAxisProp, SelectProps>;
export declare const Select: SelectAdapted & AdaptedStatics<typeof ZSelect> & { Root: SelectAdapted };

/** dialog — no vendor route; the wired surface keeps zero's names. */
type DialogProps = Record<never, never>;
type DialogAdapted = Adapted<typeof ZDialog, ZeroAxisProp, DialogProps>;
export declare const Dialog: DialogAdapted & AdaptedStatics<typeof ZDialog> & { Root: DialogAdapted };

/** field — no vendor route; the wired surface keeps zero's names. */
type FieldProps = Record<never, never>;
type FieldAdapted = Adapted<typeof ZField, ZeroAxisProp, FieldProps>;
export declare const Field: FieldAdapted & AdaptedStatics<typeof ZField> & { Root: FieldAdapted };

/** toast — no vendor route; the wired surface keeps zero's names. */
type ToastProps = Record<never, never>;
type ToastAdapted = Adapted<typeof ZToast, ZeroAxisProp, ToastProps>;
export declare const Toast: ToastAdapted & AdaptedStatics<typeof ZToast> & { Root: ToastAdapted };
