// daisyui — generated by @sigx/zero-kit. Do not edit.
//
// Augments @sigx/zero's ZeroVocabulary with this design system's compiled
// vocabulary. Opt in with:  import '@sigx/<ds>/register';
declare module '@sigx/zero' {
    interface ZeroVocabulary {
        theme: 'light' | 'dark';
        breakpoint: never;
        property: '--border' | '--color-accent' | '--color-accent-content' | '--color-accent-soft' | '--color-base-100' | '--color-base-200' | '--color-base-300' | '--color-base-content' | '--color-error' | '--color-error-content' | '--color-error-soft' | '--color-info' | '--color-info-content' | '--color-info-soft' | '--color-neutral' | '--color-neutral-content' | '--color-neutral-soft' | '--color-primary' | '--color-primary-content' | '--color-primary-soft' | '--color-secondary' | '--color-secondary-content' | '--color-secondary-soft' | '--color-success' | '--color-success-content' | '--color-success-soft' | '--color-warning' | '--color-warning-content' | '--color-warning-soft' | '--disabled-opacity' | '--duration-fast' | '--duration-normal' | '--duration-slow' | '--ease-standard' | '--font-mono' | '--font-sans' | '--leading-none' | '--leading-normal' | '--leading-tight' | '--radius-box' | '--radius-field' | '--radius-selector' | '--shadow-lg' | '--shadow-md' | '--shadow-sm' | '--shadow-xl' | '--shadow-xs' | '--size-field' | '--size-selector' | '--space-2xl' | '--space-2xs' | '--space-lg' | '--space-md' | '--space-sm' | '--space-xl' | '--space-xs' | '--tracking-normal' | '--tracking-wide' | '--weight-bold' | '--weight-medium' | '--weight-normal' | '--weight-semibold';
        tokens: {
            radius: 'selector' | 'field' | 'box';
            size: 'selector' | 'field';
            font: 'sans' | 'serif' | 'mono' | 'display';
            text: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl';
            weight: 'normal' | 'medium' | 'semibold' | 'bold';
            leading: 'none' | 'tight' | 'normal' | 'relaxed';
            tracking: 'tight' | 'normal' | 'wide';
            space: '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
            shadow: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
            duration: 'instant' | 'fast' | 'normal' | 'slow';
            ease: 'linear' | 'standard' | 'emphasized';
        };
        components: {
            /** tabs — color wired. */
            'tabs': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** collapsible — no axis wired by daisyui; every axis errors under this register module. */
            'collapsible': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** switch — color wired. */
            'switch': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** dialog — no axis wired by daisyui; every axis errors under this register module. */
            'dialog': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** popover — no axis wired by daisyui; every axis errors under this register module. */
            'popover': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** tooltip — no axis wired by daisyui; every axis errors under this register module. */
            'tooltip': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** menu — no axis wired by daisyui; every axis errors under this register module. */
            'menu': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** field — no axis wired by daisyui; every axis errors under this register module. */
            'field': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** checkbox — no axis wired by daisyui; every axis errors under this register module. */
            'checkbox': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** radio-group — no axis wired by daisyui; every axis errors under this register module. */
            'radio-group': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** progress — no axis wired by daisyui; every axis errors under this register module. */
            'progress': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** slider — no axis wired by daisyui; every axis errors under this register module. */
            'slider': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** accordion — no axis wired by daisyui; every axis errors under this register module. */
            'accordion': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** select — no axis wired by daisyui; every axis errors under this register module. */
            'select': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** button — color, size, variant wired. */
            'button': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                variant: 'solid' | 'outline' | 'soft' | 'ghost';
                axes: Record<string, never>;
            };
            /** avatar — no axis wired by daisyui; every axis errors under this register module. */
            'avatar': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** toast — color wired. */
            'toast': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** combobox — no axis wired by daisyui; every axis errors under this register module. */
            'combobox': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** toggle — color, size wired. */
            'toggle': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** toggle-group — color wired. */
            'toggle-group': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** number-input — no axis wired by daisyui; every axis errors under this register module. */
            'number-input': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** rating-group — no axis wired by daisyui; every axis errors under this register module. */
            'rating-group': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
            /** tree-view — no axis wired by daisyui; every axis errors under this register module. */
            'tree-view': {
                /** Accepts `color` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no daisyui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
            };
        };
    }
}

// Fails to compile if a scope above is not in zero's anatomy registry
// (a typo or a version skew would otherwise silently take the open
// fallback — RFC 0002 §3.1).
type _MustBeTrue<T extends true> = T;
type _ScopesValid = _MustBeTrue<
    keyof import('@sigx/zero').ZeroVocabulary['components'] extends import('@sigx/zero').ZeroScope
        ? true : false
>;
export {};
