// heroui — generated by @sigx/zero-kit. Do not edit.
//
// Augments @sigx/zero's ZeroVocabulary with this design system's compiled
// vocabulary. Opt in with:  import '@sigx/<ds>/register';
declare module '@sigx/zero' {
    interface ZeroVocabulary {
        theme: 'hero-light' | 'hero-dark';
        breakpoint: 'sm' | 'md' | 'lg';
        property: '--border' | '--color-base-100' | '--color-base-200' | '--color-base-300' | '--color-base-content' | '--disabled-opacity' | '--duration-fast' | '--duration-instant' | '--duration-normal' | '--duration-slow' | '--ease-accelerate' | '--ease-decelerate' | '--ease-linear' | '--ease-standard' | '--font-mono' | '--font-sans' | '--hero-danger' | '--hero-danger-ink' | '--hero-danger-soft' | '--hero-focus' | '--hero-line' | '--hero-muted' | '--hero-primary' | '--hero-primary-ink' | '--hero-secondary' | '--leading-none' | '--leading-normal' | '--leading-tight' | '--radius-box' | '--radius-field' | '--radius-selector' | '--shadow-lg' | '--shadow-md' | '--shadow-sm' | '--shadow-xl' | '--shadow-xs' | '--size-field' | '--size-selector' | '--space-2xl' | '--space-2xs' | '--space-lg' | '--space-md' | '--space-sm' | '--space-xl' | '--space-xs' | '--text-2xl' | '--text-3xl' | '--text-fixed-2xl' | '--text-fixed-3xl' | '--text-fixed-lg' | '--text-fixed-md' | '--text-fixed-sm' | '--text-fixed-xl' | '--text-fixed-xs' | '--text-lg' | '--text-md' | '--text-sm' | '--text-xl' | '--text-xs' | '--tracking-normal' | '--tracking-tight' | '--tracking-wide' | '--weight-bold' | '--weight-medium' | '--weight-normal' | '--weight-semibold';
        tokens: {
            radius: 'selector' | 'field' | 'box';
            size: 'selector' | 'field';
            font: 'sans' | 'serif' | 'mono' | 'display';
            text: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl';
            weight: 'normal' | 'medium' | 'semibold' | 'bold';
            leading: 'none' | 'tight' | 'normal' | 'relaxed';
            tracking: 'tight' | 'normal' | 'wide';
            space: '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
            shadow: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
            duration: 'instant' | 'fast' | 'normal' | 'slow';
            ease: 'linear' | 'standard' | 'emphasized' | 'accelerate' | 'decelerate';
        };
        components: {
            /** button — size, variant, mods.icon-only, mods.pending wired. */
            'button': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                variant: 'primary' | 'secondary' | 'tertiary' | 'outline' | 'ghost' | 'danger' | 'danger-soft';
                axes: Record<string, never>;
                mods: { 'icon-only': boolean; 'pending': boolean };
            };
            /** tabs — size wired. */
            'tabs': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** switch — size wired. */
            'switch': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** checkbox — size wired. */
            'checkbox': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** select — size wired. */
            'select': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** dialog — no axis wired by heroui; every axis errors under this register module. */
            'dialog': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** field — no axis wired by heroui; every axis errors under this register module. */
            'field': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** toast — no axis wired by heroui; every axis errors under this register module. */
            'toast': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
        };
    }
}

// Fails to compile if a scope above is not in zero's anatomy registry
// (a typo or a version skew would otherwise silently take the open
// fallback — RFC 0002 §3.1).
type _MustBeTrue<T extends true> = T;
type _ScopesValid = _MustBeTrue<
    keyof import('@sigx/zero').ZeroVocabulary['components'] extends import('@sigx/zero').ZeroScope
        ? true : false
>;
export {};
