// heroui — generated by @sigx/zero-kit. Do not edit.
//
// Augments @sigx/zero's ZeroVocabulary with this design system's compiled
// vocabulary. Opt in with:  import '@sigx/<ds>/register';
declare module '@sigx/zero' {
    interface ZeroVocabulary {
        theme: 'hero-light' | 'hero-dark';
        breakpoint: 'sm' | 'md' | 'lg';
        property: '--border' | '--color-base-100' | '--color-base-200' | '--color-base-300' | '--color-base-content' | '--disabled-opacity' | '--duration-fast' | '--duration-instant' | '--duration-normal' | '--duration-slow' | '--ease-accelerate' | '--ease-decelerate' | '--ease-linear' | '--ease-standard' | '--font-mono' | '--font-sans' | '--hero-danger' | '--hero-danger-ink' | '--hero-danger-soft' | '--hero-focus' | '--hero-line' | '--hero-muted' | '--hero-primary' | '--hero-primary-ink' | '--hero-scrim' | '--hero-secondary' | '--leading-none' | '--leading-normal' | '--leading-tight' | '--radius-box' | '--radius-field' | '--radius-selector' | '--shadow-lg' | '--shadow-md' | '--shadow-sm' | '--shadow-xl' | '--shadow-xs' | '--size-field' | '--size-selector' | '--space-2xl' | '--space-2xs' | '--space-lg' | '--space-md' | '--space-sm' | '--space-xl' | '--space-xs' | '--text-2xl' | '--text-3xl' | '--text-fixed-2xl' | '--text-fixed-3xl' | '--text-fixed-lg' | '--text-fixed-md' | '--text-fixed-sm' | '--text-fixed-xl' | '--text-fixed-xs' | '--text-lg' | '--text-md' | '--text-sm' | '--text-xl' | '--text-xs' | '--tracking-normal' | '--tracking-tight' | '--tracking-wide' | '--weight-bold' | '--weight-medium' | '--weight-normal' | '--weight-semibold';
        tokens: {
            radius: 'selector' | 'field' | 'box';
            size: 'selector' | 'field';
            font: 'sans' | 'serif' | 'mono' | 'display';
            text: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl';
            weight: 'normal' | 'medium' | 'semibold' | 'bold';
            leading: 'none' | 'tight' | 'normal' | 'relaxed';
            tracking: 'tight' | 'normal' | 'wide';
            space: '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
            shadow: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
            duration: 'instant' | 'fast' | 'normal' | 'slow';
            ease: 'linear' | 'standard' | 'emphasized' | 'accelerate' | 'decelerate';
        };
        components: {
            /** tabs — size wired. */
            'tabs': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** collapsible — size wired. */
            'collapsible': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** switch — size wired. */
            'switch': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** dialog — size wired. */
            'dialog': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** popover — size wired. */
            'popover': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** tooltip — size wired. */
            'tooltip': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** menu — size wired. */
            'menu': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** field — size wired. */
            'field': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** checkbox — size wired. */
            'checkbox': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** radio-group — size wired. */
            'radio-group': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** progress — size wired. */
            'progress': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** slider — size wired. */
            'slider': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** accordion — size wired. */
            'accordion': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** select — size wired. */
            'select': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** button — size, variant, mods.icon-only, mods.pending wired. */
            'button': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                variant: 'primary' | 'secondary' | 'tertiary' | 'outline' | 'ghost' | 'danger' | 'danger-soft';
                axes: Record<string, never>;
                mods: { 'icon-only': boolean; 'pending': boolean };
            };
            /** avatar — size wired. */
            'avatar': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** toast — size wired. */
            'toast': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** combobox — size wired. */
            'combobox': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** toggle — size wired. */
            'toggle': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** toggle-group — size wired. */
            'toggle-group': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** number-input — size wired. */
            'number-input': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** rating-group — size wired. */
            'rating-group': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** tree-view — size wired. */
            'tree-view': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** input — size wired. */
            'input': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** textarea — size wired. */
            'textarea': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** native-select — size wired. */
            'native-select': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** card — size wired. */
            'card': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** alert — size wired. */
            'alert': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** badge — size wired. */
            'badge': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** divider — size wired. */
            'divider': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** skeleton — size wired. */
            'skeleton': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** spinner — size wired. */
            'spinner': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** kbd — size wired. */
            'kbd': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** status — size wired. */
            'status': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** indicator — size wired. */
            'indicator': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** stats — size wired. */
            'stats': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** timeline — size wired. */
            'timeline': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** chat — size wired. */
            'chat': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** radial-progress — size wired. */
            'radial-progress': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** join — size wired. */
            'join': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** navbar — size wired. */
            'navbar': {
                /** Accepts `color` at runtime, but heroui declares no color axis at all — the attribute would match nothing. */
                color: never;
                size: 'sm' | 'md' | 'lg';
                /** Accepts `variant` at runtime, but no heroui recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
        };
    }
}

// Fails to compile if a scope above is not in zero's anatomy registry
// (a typo or a version skew would otherwise silently take the open
// fallback — docs/architecture.md, "The register artifact").
type _MustBeTrue<T extends true> = T;
type _ScopesValid = _MustBeTrue<
    keyof import('@sigx/zero').ZeroVocabulary['components'] extends import('@sigx/zero').ZeroScope
        ? true : false
>;
// Fails to compile if any entry above drops one of the five members.
// A dropped key is not a smaller entry: the vocabulary resolvers fall
// back to the OPEN union for a member they cannot find, so a truncated
// entry silently un-narrows the axis it omitted (#316).
type _EntryShape = {
    color: string; size: string; variant: string;
    axes: Record<string, string>; mods: Record<string, boolean>;
};
type _Entries = import('@sigx/zero').ZeroVocabulary['components'];
type _EntriesValid = _MustBeTrue<
    { [K in keyof _Entries]: _Entries[K] extends _EntryShape ? true : false }[keyof _Entries] extends true
        ? true : false
>;
export {};
